/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Posix */

#ifndef _Included_Posix
#define _Included_Posix
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Posix
 * Method:    setenv
 * Signature: (Ljava/lang/String;Ljava/lang/String;Z)I
 */
JNIEXPORT jint JNICALL Java_Posix_setenv
  (JNIEnv *, jclass, jstring, jstring, jboolean);

/*
 * Class:     Posix
 * Method:    getenv
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Posix_getenv
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif